name: Setup git
description: Setup git

inputs:
  name:
    description: user name
    required: false
    default: taiga-family-bot
  email:
    description: user email
    required: false
    default: opensource@tinkoff.ru
  token:
    description: Token
    required: true

outputs:
  git-has-been-changed:
    description: Modified status
    value: ${{ steps.output.outputs.git-has-been-changed }}

runs:
  using: composite
  steps:
    - name: Setup GIT
      shell: bash
      run: |
        git config user.name "${{ inputs.name }}"
        git config user.email "${{ inputs.email }}"
        git config remote.origin.url https://x-access-token:${{ inputs.token }}@github.com/$GITHUB_REPOSITORY
        git remote update

        echo "Last 5 tags:"
        git tag --sort=committerdate | tail -5

    - id: output
      shell: bash
      run: |
        echo "git-has-been-changed=$([[ "$(git status --porcelain)" ]] && echo "true" || echo "false")" >> $GITHUB_OUTPUT
