name: Action for merge me
description: Action for merge me

inputs:
  token:
    description: Token
    required: true
  username:
    required: false
    description: Bot name
    default: taiga-family-bot
  type:
    description: >
      Represents available types of methods to use when merging a pull request.
      One of: MERGE, STASH or REBASE
    required: false
    default: SQUASH

runs:
  using: composite
  steps:
    - run: sleep 30s
      shell: bash

    - uses: ridedott/merge-me-action@v2.10.54
      continue-on-error: true
      with:
        GITHUB_LOGIN: ${{ inputs.username }}
        GITHUB_TOKEN: ${{ inputs.token }}
        MERGE_METHOD: ${{ inputs.type }}
        ENABLE_GITHUB_API_PREVIEW: "true"
        ENABLED_FOR_MANUAL_CHANGES: true
        MAXIMUM_RETRIES: 2

    - uses: actions/github-script@v6
      continue-on-error: true
      with:
        github-token: ${{ github.token }}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '⚡️ Run auto merge for current branch!'
          })
