name: Action for merge me
description: Action for merge me

inputs:
  token:
    description: Token
    required: true
  login:
    required: false
    description: Bot name
    default: taiga-family-bot
  merge-method:
    description: >
      Represents available types of methods to use when merging a pull request.
      One of: MERGE, STASH or REBASE
    required: false
    default: SQUASH

runs:
  using: composite
  steps:
    - run: sleep 120s
      shell: bash

    - uses: actions/checkout@v4.1.0
    - uses: imba-tjd/rebase-upstream-action@0.5
      with:
        upstream: $GITHUB_REPOSITORY
        branch: ${{ github.base_ref }}
        push: false
    - name: Abort rebase when merge conflict
      if: failure()
      shell: bash
      run: |
        git status
        git rebase --abort
        git status

    - id: string
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ inputs.merge-method }}
    - name: Mark auto merge for Pull Request
      continue-on-error: true
      shell: bash
      run: gh pr merge --${{ steps.string.outputs.lowercase }} --auto "${{ github.event.number }}"
      env:
        GH_TOKEN: ${{ inputs.token }}

    - uses: ridedott/merge-me-action@v2.10.54
      continue-on-error: true
      with:
        GITHUB_LOGIN: ${{ inputs.login }}
        GITHUB_TOKEN: ${{ inputs.token }}
        MERGE_METHOD: ${{ inputs.merge-method }}
        ENABLE_GITHUB_API_PREVIEW: true
        ENABLED_FOR_MANUAL_CHANGES: true
        MAXIMUM_RETRIES: 1

    - uses: actions/github-script@v6
      continue-on-error: true
      with:
        github-token: ${{ github.token }}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '⚡️ Run auto merge for current branch!'
          })
