name: Action for merge me
description: Action for merge me

inputs:
  token:
    description: Token
    required: true
  login:
    required: false
    description: Bot name
    default: taiga-family-bot
  merge-method:
    description: >
      Represents available types of methods to use when merging a pull request. One of: MERGE, STASH or REBASE
    required: false
    default: SQUASH

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4.3.1

    - id: string
      uses: ASzc/change-string-case-action@v6
      with:
        string: ${{ inputs.merge-method }}
    - name: Mark auto merge for Pull Request
      id: auto-merge
      continue-on-error: true
      shell: bash
      run: gh pr merge --${{ steps.string.outputs.lowercase }} --auto "${{ github.event.number }}"
      env:
        GH_TOKEN: ${{ inputs.token }}
