name: Dependency review
description: Dependency review

inputs:
  severity:
    description: severity
    required: false
    default: "critical"

runs:
  using: composite
  steps:
    - name: Dependency Review
      uses: actions/dependency-review-action@v4.2.3
      with:
        fail-on-severity: ${{ inputs.severity }}
