name: Auto approve by single user
description: Auto approve by single user

inputs:
  token:
    description: Token
    required: true

runs:
  using: "composite"
  steps:
    - uses: hmarr/auto-approve-action@v4.0.0
      with:
        review-message: "LGTM (Automated approved)"
        github-token: ${{ inputs.token }}
