name: Check Playwright Diffs
description: Uploads diff artifacts, and fails if diffs exist.

inputs:
  pw-result:
    description: Path to Playwright results folder
    required: true
  retry-count:
    description: Retry count folder suffix
    required: true
    default: '2'
  playwright-snapshots-artifacts-key:
    description: Artifact name key
    required: true

runs:
  using: composite
  steps:
    - name: Upload artifacts / ${{ inputs.playwright-snapshots-artifacts-key }}
      uses: actions/upload-artifact@v4.6.2
      with:
        path: ${{ inputs.pw-result }}/**/*-retry${{ inputs.retry-count }}/**/*.diff.png
        name: ${{ inputs.playwright-snapshots-artifacts-key }}
        if-no-files-found: ignore
        compression-level: 0
        retention-days: 1

    - name: Check if diff-output exists
      id: diff_checker
      run: |
        echo "diff_exist=$(find '${{ inputs.pw-result }}' -iname '*.diff.png' | wc -l | sed -e 's/^[[:space:]]*//')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Fail with error if diff-output exists
      if: ${{ steps.diff_checker.outputs.diff_exist != '0' }}
      run: |
        find '${{ inputs.pw-result }}' -iname '*.diff.png' -exec echo "{}" \;
        exit 1
      shell: bash
