name: Check Playwright Diffs
description: Uploads diff artifacts, and fails if diffs exist.

inputs:
  pw-result:
    description: Path to Playwright results folder
    required: true

runs:
  using: composite
  steps:
    - name: Check if diff-output exists
      id: diff_checker
      run: |
        echo "diff_exist=$(find '${{ inputs.pw-result }}' -iname '*.diff.png' | wc -l | sed -e 's/^[[:space:]]*//')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Fail with error if diff-output exists
      if: ${{ steps.diff_checker.outputs.diff_exist != '0' }}
      run: |
        find '${{ inputs.pw-result }}' -iname '*.diff.png' -exec echo "{}" \;
        exit 1
      shell: bash
