name: Auto-push action
description: Auto-push action

inputs:
  token:
    description: token
    required: true
  name:
    description: commit username
    required: false
    default: taiga-family-bot
  email:
    description: user email
    required: false
    default: opensource@tbank.ru
  message:
    description: commit message
    required: false
    default: apply changes after linting

runs:
  using: composite
  steps:
    - name: Commit and push
      shell: bash
      run: |
        
        git checkout ${{ github.head_ref }}

        if [[ "${{ github.event.pull_request.head.repo.full_name != github.repository }}" == "true" ]]; then
            echo "Auto push doesn't support"
            exit 0;
        fi

        git config --global user.name "${{ inputs.name }}"
        git config --global user.email "${{ inputs.email }}"
        git config remote.origin.url https://${{ inputs.name }}:${{ inputs.token }}@github.com/${{ github.repository }}

        git add .

        if [[ `git status --porcelain` ]]; then
           git commit --author="${{ inputs.name }} <${{ inputs.name }}@users.noreply.github.com>" \
                      -m "chore: ${{ inputs.message }} [bot]" \
                      --no-verify
           git push -u origin ${{ github.head_ref }} --force-with-lease
        else
           echo "Nothing to update"
        fi
