name: Auto-push action
description: Auto-push action

inputs:
  token:
    description: token
    required: true
  name:
    description: commit username
    required: false
    default: taiga-family-bot
  email:
    description: user email
    required: false
    default: opensource@tinkoff.ru
  message:
    description: commit message
    required: false
    default: apply changes after linting

runs:
  using: composite
  steps:
    - name: Commit and push
      shell: bash
      run: |
        git config --global user.name "${{ inputs.name }}"
        git config --global user.email "${{ inputs.email }}"
        git config remote.origin.url https://${{ inputs.name }}:${{ inputs.token }}@github.com/$GITHUB_REPOSITORY

        git add .
        git status --untracked-files=no
        git commit --author="${{ inputs.name }} <${{ inputs.name }}@users.noreply.github.com>" -m "chore: ${{ inputs.message }} [bot]" --no-verify
        git push origin ${{ github.head_ref }} &>/dev/null
