name: Auto-push action
description: Auto-push action

inputs:
  token:
    description: token
    required: true
  name:
    description: commit username
    required: false
    default: taiga-family-bot
  email:
    description: user email
    required: false
    default: 41898282+github-actions[bot]@users.noreply.github.com
  message:
    description: commit message
    required: false
    default: apply changes after linting

runs:
  using: composite
  steps:
    - name: Commit and push
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        NAME: ${{ inputs.name }}
        EMAIL: ${{ inputs.email }}
        MESSAGE: ${{ inputs.message }}
        BASE_REF: ${{ github.base_ref }}
        HEAD_REF: ${{ github.head_ref }}
        HEAD_REPO: ${{ github.event.pull_request.head.repo.full_name }}
        REPOSITORY: ${{ github.repository }}
      run: |
        if [[ -z "$BASE_REF" ]]; then
            echo "Auto push doesn't support when base_ref is empty"
            exit 0
        fi

        if [[ "$HEAD_REPO" != "$REPOSITORY" ]]; then
            echo "Auto push doesn't support from fork"
            exit 0
        fi

        git config user.name "$NAME"
        git config user.email "$EMAIL"
        git remote set-url origin "https://x-access-token:${TOKEN}@github.com/${REPOSITORY}.git"

        git add .

        if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "chore: ${MESSAGE} [bot]" --no-verify
            git push origin "HEAD:${HEAD_REF}"
        else
            echo "Nothing to update"
        fi
