name: Auto-push action
description: Auto-push action

inputs:
  token:
    description: token
    required: true
  username:
    description: commit username
    required: false
    default: taiga-family-bot
  message:
    description: commit message
    required: false
    default: apply changes after linting

runs:
  using: composite
  steps:
    - name: Commit and push
      shell: bash
      run: |
        git config user.name "${{ inputs.username }}"
        git config user.email "taiga-ui@users.noreply.github.com"
        git config remote.origin.url https://x-access-token:${{ inputs.token }}@github.com/$GITHUB_REPOSITORY

        git add .
        git status
        git commit -m "${{ inputs.message }}"
        git push
