name: Auto-push action
description: Auto-push action

inputs:
  token:
    description: token
    required: true
  name:
    description: commit username
    required: false
    default: taiga-family-bot
  email:
    description: user email
    required: false
    default: 41898282+github-actions[bot]@users.noreply.github.com
  message:
    description: commit message
    required: false
    default: apply changes after linting

runs:
  using: composite
  steps:
    - name: Commit and push
      shell: bash
      run: |

        if [[ "${{ github.base_ref }}" == "" ]]; then
            echo "Auto push doesn't support when base_ref is empty"
            exit 0;
        fi

        if [[ "${{ github.event.pull_request.head.repo.full_name != github.repository }}" == "true" ]]; then
            echo "Auto push doesn't support from fork"
            exit 0;
        fi

        git add .
        git stash || echo 'No local changes to save'
        git remote update &> /dev/null
        git fetch &> /dev/null
        git checkout -t -b ${{ github.head_ref }} origin/${{ github.head_ref }} || echo 'Already exists'
        git stash pop || echo 'Already updated'
        git add .
        git status --porcelain

        git config --global user.name "${{ inputs.name }}"
        git config --global user.email "${{ inputs.email }}"
        git remote set-url --push origin https://${{ inputs.name }}:${{ inputs.token }}@github.com/${{ github.repository }}

        if [[ `git status --porcelain` ]]; then
           git commit --author="${{ inputs.name }} <${{ inputs.name }}@users.noreply.github.com>" \
                      -m "chore: ${{ inputs.message }} [bot]" \
                      --no-verify
           git push -u origin ${{ github.head_ref }}
        else
           echo "Nothing to update"
        fi
