name: Auto-push action
description: Auto-push action

inputs:
  username:
    description: commit username
    required: false
    default: taiga-family-bot
  message:
    description: commit message
    required: false
    default: apply changes after linting

runs:
  using: composite
  steps:
    - name: Git status
      shell: bash
      run: |
        git add .
        git status

    - name: Push
      uses: stefanzweifel/git-auto-commit-action@v4.16.0
      with:
        commit_user_name: "${{ inputs.username }}"
        commit_user_email: "${{ inputs.username }}@users.noreply.github.com"
        commit_author: "${{ inputs.username }} <${{ inputs.username }}@users.noreply.github.com>"
        commit_message: "chore: ${{ inputs.message }} [bot]"
        status_options: "--untracked-files=no"
        commit_options: "--no-verify"
        skip_fetch: true
