name: Combine Cypress Diffs
description: Combines Playwright failed screenshots

runs:
  using: composite
  steps:
    - name: Combine images to get diff reports
      run: |
        npm install @taiga-ui/testing --no-save --silent --force
        npx ts-node -e "import { tuiCombineCypressFailedScreenshots as run } from '@taiga-ui/testing/visual-testing'; run();";
      shell: bash
