name: Combine Cypress Diffs
description: Combines Playwright failed screenshots

runs:
  using: composite
  steps:
    - name: Combine images to get diff reports
      run: |
        if ! node -e "require('@taiga-ui/testing')" 2>/dev/null; then
          npm install --ignore-scripts --cpu=$(node -p process.arch) --os=$(node -p process.platform) @taiga-ui/testing sharp --no-save --force
        fi
        npx ts-node -O '{"moduleResolution":"node10"}' -e "import { tuiCombineCypressFailedScreenshots as run } from '@taiga-ui/testing/visual-testing'; run();";
      shell: bash
