name: Setup npm
description: Setup npm

inputs:
  token:
    description: Token
    required: true

runs:
  using: composite
  steps:
    - name: Setup GIT
      shell: bash
      run: |
        npm config set '//registry.npmjs.org/:_authToken' "${{ inputs.token }}"

        if ! NPM_WHOAMI_OUTPUT=$(npm whoami 2>&1); then
          echo -e "Token is invalid or expired: ${NPM_WHOAMI_OUTPUT}"
          exit 1
        fi

        echo "npm whoami: ${NPM_WHOAMI_OUTPUT}"
