name: Rebase
description: Rebase

runs:
  using: composite
  steps:
    - name: Try rebase locally for check affected
      uses: imba-tjd/rebase-upstream-action@0.5
      with:
        upstream: $GITHUB_REPOSITORY
        branch: ${{ github.base_ref }}
        push: false

    - name: Abort rebase when merge conflict
      if: failure()
      shell: bash
      run: |
        git status
        git rebase --abort
        git status
