name: Rebase action
description: Rebase action

runs:
  using: composite
  steps:
    - name: Try rebase locally for check affected
      uses: imba-tjd/rebase-upstream-action@0.10
      with:
        upstream: ${{ github.repository }}
        branch: ${{ github.base_ref }}
        push: false

    - name: Abort rebase when merge conflict
      if: failure()
      shell: bash
      run: |
        git status
        git rebase --abort
        git status
