name: Dependency review
description: Dependency review

inputs:
  severity:
    description: severity
    required: false
    default: 'critical'

runs:
  using: composite
  steps:
    - name: Dependency Review
      uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
      with:
        fail-on-severity: ${{ inputs.severity }}
