name: Action for get info about Node.js workspace
description: Node.js workspace

inputs:
  node-version:
    description: Node.js version
    deprecationMessage: 'Not relevant'
    required: false
    default: 24.x
  node-registry:
    description: Registry
    deprecationMessage: 'Not relevant'
    required: false

outputs:
  root-package-version:
    description: Full version of root package.json (x.y.z)
    value: ${{ steps.output.outputs.root-package-version }}
  root-package-major-version:
    description: Only major version of root package.json (x)
    value: ${{ steps.output.outputs.root-package-major-version }}
  is-release-candidate:
    description: root package.json includes -rc
    value: ${{ steps.output.outputs.is-release-candidate }}

runs:
  using: composite
  steps:
    - uses: taiga-family/ci/actions/setup/variables@main
    - uses: taiga-family/ci/actions/setup/node@main

    - id: output
      shell: bash
      run: |
        echo "root-package-version=v$(node -p "require('./package.json')?.version")" >> $GITHUB_OUTPUT
        echo "root-package-major-version=$(node -p "parseInt(require('./package.json')?.version)")" >> $GITHUB_OUTPUT
        echo "is-release-candidate=$(node -p "require('./package.json')?.version?.includes('rc')")" >> $GITHUB_OUTPUT
