name: Setup variables
description: Setup variables

runs:
  using: composite
  steps:
    - name: Additional logs for improving debug of environments
      shell: bash
      run: |
        echo "github.actor: ${{ github.actor }}"
        echo "github.workflow: ${{ github.workflow }}"
        echo "github.sha: ${{ github.sha }}"
        echo "github.ref: ${{ github.ref }}"
        echo "github.ref_name: ${{ github.ref_name }}"
        echo "github.ref_type: ${{ github.ref_type }}"
        echo "github.base_ref: ${{ github.base_ref }}"
        echo "github.head_ref: ${{ github.head_ref }}"
        echo "github.run_id: ${{ github.run_id }}"
        echo "github.run_number: ${{ github.run_number }}"
        echo "github.run_attempt: ${{ github.run_attempt }}"
        echo "github.event.number: ${{ github.event.number }}"
        echo "github.event.pull_request.head.ref: ${{ github.event.pull_request.head.ref }}"
        echo "github.event.pull_request.head.repo.full_name: ${{ github.event.pull_request.head.repo.full_name }}"

    - shell: bash
      run: |
        echo "Provide global variables ..."

        export TUI_CI="true"
        export NG_SERVER_PORT="3333"
        export NPM_CONFIG_CACHE="~/.npm"
        export NX_BRANCH="${{ github.event.number }}"
        export DIST="dist/demo"
        export DIST_NEXT="dist/demo/${{ github.base_ref }}"
        export REPO="https://github.com/$GITHUB_REPOSITORY"
        export IS_MAIN_BRANCH="${{ github.ref == 'refs/heads/main' }}"
        export IS_RELEASE_BRANCH="${{ contains(github.head_ref, 'release/') }}"
        export CI_COMMIT_SHA="${{ github.event.pull_request.head.sha || github.sha }}"
        export CACHE_DIST_KEY="dist-${{ github.head_ref }}-${{ github.ref }}-${{ github.sha }}"
        export IS_FORK="${{ github.event.pull_request.head.repo.full_name != github.repository }}"
        export IS_DEPENDABOT="${{ github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' }}"
        export SNAPSHOTS_PATH="./apps/demo-integrations/cypress/snapshots"
        export SNAPSHOTS_CACHE_KEY="e2e-cache--${{ github.event.pull_request.head.sha || github.sha }}-${{ github.event.number }}"
        export SNAPSHOTS_ARTIFACTS_KEY="e2e-artifacts--${{ github.event.pull_request.head.sha || github.sha }}-${{ github.run_id }}-${{ github.event.number }}"

        if [[ "$IS_FORK" == "false" && "$IS_DEPENDABOT" == "false" ]]; then
            export IS_OWNER_MODE="true"
        else
            export IS_OWNER_MODE="false"
        fi

        if [[ "$IS_FORK" == "false" && "$IS_DEPENDABOT" == "false" && "$IS_MAIN_BRANCH" == "false" ]]; then
            export SUPPORT_AUTO_PUSH="true"
        else
            export SUPPORT_AUTO_PUSH="false"
        fi

        echo "TUI_CI=$TUI_CI" >> $GITHUB_ENV
        echo "NPM_CONFIG_CACHE=$NPM_CONFIG_CACHE" >> $GITHUB_ENV
        echo "NX_BRANCH=$NX_BRANCH" >> $GITHUB_ENV
        echo "IS_FORK=$IS_FORK" >> $GITHUB_ENV
        echo "DIST=$DIST" >> $GITHUB_ENV
        echo "DIST_NEXT=$DIST_NEXT" >> $GITHUB_ENV
        echo "REPO=$REPO" >> $GITHUB_ENV
        echo "NG_SERVER_PORT=$NG_SERVER_PORT" >> $GITHUB_ENV
        echo "IS_MAIN_BRANCH=$IS_MAIN_BRANCH" >> $GITHUB_ENV
        echo "CI_COMMIT_SHA=$CI_COMMIT_SHA" >> $GITHUB_ENV
        echo "CACHE_DIST_KEY=$CACHE_DIST_KEY" >> $GITHUB_ENV
        echo "IS_RELEASE_BRANCH=$IS_RELEASE_BRANCH" >> $GITHUB_ENV
        echo "IS_DEPENDABOT=$IS_DEPENDABOT" >> $GITHUB_ENV
        echo "IS_OWNER_MODE=$IS_OWNER_MODE" >> $GITHUB_ENV
        echo "SUPPORT_AUTO_PUSH=$SUPPORT_AUTO_PUSH" >> $GITHUB_ENV
        echo "SNAPSHOTS_PATH=$SNAPSHOTS_PATH" >> $GITHUB_ENV
        echo "SNAPSHOTS_ARTIFACTS_KEY=$SNAPSHOTS_ARTIFACTS_KEY" >> $GITHUB_ENV
        echo "SNAPSHOTS_CACHE_KEY=$SNAPSHOTS_CACHE_KEY" >> $GITHUB_ENV
