name: Action for wait job
description: Action for wait job

inputs:
  token:
    description: Token
    required: true
  job:
    description: Job name
    required: true

runs:
  using: composite
  steps:
    - uses: fountainhead/action-wait-for-check@v1.2.0
      id: waiter
      with:
        token: ${{ inputs.token }}
        checkName: ${{ inputs.job }}
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
        timeoutSeconds: 10800
        intervalSeconds: 90

    - run: echo "Current status ~ ${{ steps.waiter.outputs.conclusion }}"
      shell: bash

    - if: steps.waiter.outputs.conclusion != 'success'
      shell: bash
      run: exit 1
