name: Auto-cleanup cache from branch
description: Auto-cleanup cache from branch

inputs:
  branch-name:
    description: Branch name
    required: true

runs:
  using: composite
  steps:
    - name: Git status
      shell: bash
      run: |
        gh extension install actions/gh-actions-cache

        echo "Fetching list of cache key"
        cacheKeysForPR=$(gh actions-cache list -R ${{ github.repository }} -B ${{ inputs.branch-name }} | cut -f 1)

        ## Setting this to not fail the workflow while deleting cache keys.
        set +e
        echo "Deleting caches..."

        for cacheKey in $cacheKeysForPR
        do
          echo "Delete: $cacheKey"
          gh actions-cache delete $cacheKey -R ${{ github.repository }} -B ${{ inputs.branch-name }} --confirm
        done
        echo "Done"
