name: Action for checkout git
description: Action for checkout git

inputs:
  token:
    description: Token
    required: false

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        export HAS_TOKEN=$([ -z "${{ inputs.token }}" ] && echo "false" || echo "true")

    - name: Checkout with token
      if: env.HAS_TOKEN == 'true'
      uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 0
        submodules: recursive
        token: ${{ inputs.token }}

    - name: Checkout without token
      if: env.HAS_TOKEN == 'false'
      uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 0
        submodules: recursive
