name: Action for checkout git
description: Action for checkout git

inputs:
  token:
    description: Token
    required: false
  fetch-depth:
    description: Fetch depth
    default: "1"
    required: false
  fetch-tags:
    description: Fetch tags
    default: "false"
    required: false
  submodules:
    description: submodules
    default: recursive
    required: false

runs:
  using: composite
  steps:
    - shell: bash
      id: checks
      run: |
        echo "has-token=$([ -z "${{ inputs.token }}" ] && echo "false" || echo "true")" >> $GITHUB_OUTPUT

    - uses: actions/checkout@v4.1.0
      if: steps.checks.outputs.has-token == 'true'
      with:
        token: ${{ inputs.token }}
        persist-credentials: false
        ref: ${{ github.head_ref }}
        fetch-depth: ${{ inputs.fetch-depth }}
        fetch-tags: ${{ inputs.fetch-tags }}
        submodules: ${{ inputs.submodules }}

    - uses: actions/checkout@v4.1.0
      if: steps.checks.outputs.has-token == 'false'
      with:
        persist-credentials: false
        ref: ${{ github.head_ref }}
        fetch-depth: ${{ inputs.fetch-depth }}
        fetch-tags: ${{ inputs.fetch-tags }}
        submodules: ${{ inputs.submodules }}
