name: Action for checkout git
description: Action for checkout git

inputs:
  token:
    description: Token
    required: false

runs:
  using: composite
  steps:
    - shell: bash
      id: checks
      run: |
        echo "has-token=$([ -z "${{ inputs.token }}" ] && echo "false" || echo "true")" >> $GITHUB_OUTPUT

    - name: Checkout with token
      if: steps.checks.outputs.has-token == 'true'
      uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 0
        submodules: recursive
        token: ${{ inputs.token }}
        fetch-tags: true

    - name: Checkout without token
      if: steps.checks.outputs.has-token == 'false'
      uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 0
        submodules: recursive
        fetch-tags: true
