name: Action for checkout git
description: Action for checkout git

inputs:
  token:
    description: Token
    required: false

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 0
        submodules: recursive
        persist-credentials: false
        ref: $GITHUB_REF
        token: ${{ inputs.token }}
