name: 🤖 Auto approve by two user

inputs:
  token1:
    required: true
  token2:
    required: true

runs:
  using: "composite"
  steps:
    - uses: hmarr/auto-approve-action@v3.2.1
      with:
        review-message: "LGTM (Automated approved)"
        github-token: ${{ inputs.token1 }}
    - uses: hmarr/auto-approve-action@v3.2.1
      with:
        review-message: "LGTM (Automated approved)"
        github-token: ${{ inputs.token2 }}
