name: Action for Playwright
description: Playwright

inputs:
  version:
    description: custom version
    required: true
  deps:
    description: Concrete dependencies instead all
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Detect Playwright version
      id: detect-pw
      shell: bash
      run: |
        VERSION=$(npm ls @playwright/test --depth=0 --json 2>/dev/null \
          | jq -r '.dependencies["@playwright/test"].version // ""' 2>/dev/null)
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"

    - uses: actions/cache@v4.2.4
      id: playwright-cache
      with:
        path: |
          ~/Library/Caches/ms-playwright
          ~/.cache/ms-playwright
          **/node_modules/playwright
        key: ${{ runner.os }}-playwright-${{ steps.detect-pw.outputs.version || inputs.version }}

    - name: Clean install Playwright dependencies
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        npx playwright install --with-deps ${{ inputs.deps }}
        npx playwright install-deps
