name: Action for Playwright
description: Playwright

inputs:
  version:
    description: pw version
    required: true
  playwright-version:
    description: pw version
    deprecationMessage: Please use just version field
    required: true
  deps:
    description: Concrete dependencies instead all
    required: false
    default: ''

runs:
  using: composite
  steps:
    - uses: actions/cache@v4.2.3
      id: playwright-cache
      with:
        path: |
          ~/Library/Caches/ms-playwright
          ~/.cache/ms-playwright
          **/node_modules/playwright
        key: ${{ runner.os }}-playwright-${{ inputs.playwright-version || inputs.version }}

    - name: Clean install Playwright dependencies
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        npx playwright install --with-deps ${{ inputs.deps }}
        npx playwright install-deps
