name: Action for Playwright
description: Playwright

inputs:
  version:
    description: custom version
    required: true
  deps:
    description: Concrete dependencies instead all
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Detect Playwright version
      id: detect-pw
      shell: bash
      run: |
        VERSION=$(npm ls @playwright/test --all --json 2>/dev/null \
          | jq -r '.. | objects | select(has("version") and has("resolved")) | select(.resolved | contains("@playwright/test")) | .version // empty' \
          | head -n 1)

        echo "version=$VERSION" >> "$GITHUB_OUTPUT"

    - uses: actions/cache@v4.3.0
      id: playwright-cache
      with:
        path: |
          ~/Library/Caches/ms-playwright
          ~/.cache/ms-playwright
          **/node_modules/playwright
        key: ${{ runner.os }}-playwright-${{ steps.detect-pw.outputs.version || inputs.version }}

    - name: Clean install Playwright dependencies
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        npx playwright install --with-deps ${{ inputs.deps }}
        npx playwright install-deps
