name: Announce
description: Release announcement

inputs:
  url:
    description: Webhook url
    required: true
  version:
    description: Release version
    required: true
  username:
    description: username
    required: false
    default: Taiga release
  channel:
    description: Channel
    required: true

runs:
  using: composite
  steps:
    - name: Announce
      shell: bash
      run: |
        curl --http1.1 -X POST -H "Content-Type: application/json" -d '{"text": "New version [v${{ inputs.version }}](https://github.com/$GITHUB_REPOSITORY/releases/tag/v${{ inputs.version }}) released :tada:", "username": "${{ inputs.username }}", "channel": "${{ inputs.channel }}"}' ${{ inputs.url }}
