name: Combine Playwright Diffs
description: Combines Playwright failed screenshots

runs:
  using: composite
  steps:
    - name: Combine images to get diff reports
      run: |
        npm install --cpu=$(node -p process.arch) --os=$(node -p process.platform) @taiga-ui/testing sharp --no-save --force
        npx ts-node -e "import { tuiCombinePlaywrightFailedScreenshots as run } from '@taiga-ui/testing/visual-testing'; run();"
      shell: bash
