name: Action for serving web server
description: Web server

inputs:
  deps:
    description: Dependencies
    required: false
    default: chromium

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        npx envinfo --preset playwright
        npx playwright install --with-deps ${{ inputs.deps }}
