name: Action for release
description: Action for release

inputs:
  ref:
    description: GitHub ref
    required: false
  githubToken:
    description: GitHub token
    required: true
  npmToken:
    description: NPM token
    required: false
  mode:
    description: Increment mode
    required: false
  flags:
    description: Custom flags
    required: false
    default: ''

outputs:
  released:
    description: was the version updated
    value: ${{ steps.output.outputs.released }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4.3.1
      with:
        token: ${{ inputs.githubToken }}
        ref: ${{ inputs.ref || github.ref }}
        persist-credentials: false
        fetch-tags: true
        fetch-depth: 0
    - uses: taiga-family/ci/actions/setup/variables@main
    - uses: taiga-family/ci/actions/setup/node@main
    - uses: taiga-family/ci/actions/setup/config/git@main
      with:
        token: ${{ inputs.githubToken }}
    - uses: taiga-family/ci/actions/setup/config/npm@main
      if: ${{ inputs.npmToken }}
      with:
        token: ${{ inputs.npmToken }}

    - shell: bash
      id: output
      run: |

        export GITHUB_TOKEN="${{ inputs.githubToken }}"
        export HISTORY="$(git log $(git describe --tags --abbrev=0)..@ --no-merges --oneline --grep='^feat' --grep='^fix' --grep='^refactor' --grep='^perf' --grep='^breaking' --grep='^deprecate')"
        export prev_version=$(node -p "require('./package.json')?.version")

        if [[ "${{ inputs.mode }}" == "" ]]; then
          if [[ "$HISTORY" == "" ]]; then
            echo "Nothing found for release..."
            echo "released=false" >> $GITHUB_OUTPUT
            exit 0;
          else
            echo "History found: \n"
            printf '%s\n' "$HISTORY"
            echo "\n\n"
          fi;
        fi;

        if [[ "${{ inputs.mode }}" == "alpha" || "${{ inputs.mode }}" == "prerelease" ]]; then
          npx release-it --preRelease=alpha --ci ${{ inputs.flags }}
        else
          npx release-it ${{ inputs.mode }} --ci ${{ inputs.flags }}
        fi

        export new_version=$(node -p "require('./package.json')?.version")

        if [[ "$new_version" != "$prev_version" ]]; then
          echo "released=true" >> $GITHUB_OUTPUT
        else
          echo "released=false" >> $GITHUB_OUTPUT
        fi
