name: Action for release
description: Action for release

inputs:
  ref:
    description: GitHub ref
    required: true
  githubToken:
    description: GitHub token
    required: true
  npmToken:
    description: NPM token
    required: true
  forcePush:
    description: GitHub token
    required: true
  mode:
    description: NPM token
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4.1.7

    - uses: taiga-family/ci/actions/setup/checkout@v1.62.14
      with:
        token: ${{ inputs.githubToken }}
        ref: ${{ inputs.ref }}
        fetch-depth: 0
    - uses: taiga-family/ci/actions/setup/variables@v1.62.14
    - uses: taiga-family/ci/actions/setup/node@v1.62.14
    - uses: taiga-family/ci/actions/setup/config/git@v1.62.14
      with:
        token: ${{ inputs.githubToken }}
    - uses: taiga-family/ci/actions/setup/config/npm@v1.62.14
      with:
        token: ${{ inputs.npmToken }}

    - shell: bash
      run: |
        export GITHUB_TOKEN="${{ inputs.githubToken }}"

        if [[ "${{ inputs.forcePush }}" == "true" ]]; then

          if [[ "${{ inputs.mode }}" != "prepatch" ]]; then
              npx release-it "${{ inputs.mode }}" --increment --ci
          else
              npx release-it --preRelease=alpha --ci
          fi

        else
            npx release-it --increment --ci
        fi
