name: Action for Node.js
description: Node.js setup cache

inputs:
  node-version:
    description: Node.js version
    required: false
    default: 18.x
  node-registry:
    description: Registry
    required: false
    default: "https://registry.npmjs.org"
  node-path:
    description: nested node path
    required: false
    default: |
      .nx/
      node_modules/
      **/node_modules/
      **/.eslintcache

outputs:
  root-package-version:
    description: Full version of root package.json (x.y.z)
    value: ${{ steps.output.outputs.root-package-version }}
  root-package-major-version:
    description: Only major version of root package.json (x)
    value: ${{ steps.output.outputs.root-package-major-version }}
  is-release-candidate:
    description: root package.json includes -rc
    value: ${{ steps.output.outputs.is-release-candidate }}

runs:
  using: composite
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4.0.0
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.node-registry }}

    - name: Restore node_modules from cache
      id: cache-node-modules
      uses: actions/cache@v3.3.2
      with:
        path: ${{ inputs.node-path }}
        key: ${{ runner.os }}-node-${{ inputs.node-version }}__${{ hashFiles('**/package-lock.json') }}

    - shell: bash
      run: echo "CYPRESS_CACHE_FOLDER=./node_modules/cache-cypress" >> $GITHUB_ENV

    - shell: bash
      run: |
        npm set strict-ssl false
        npm config set fetch-retries 5
        npm config set fetch-retry-mintimeout 600000
        npm config set fetch-retry-maxtimeout 1200000
        npm config set fetch-timeout 1800000

    - shell: bash
      run: |
        echo "Show environment Node.js, npm ..."
        node -v
        npm -v

    - name: Clean install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      id: clean-install
      run: npm ci --include-workspace-root --audit=false --fund=false
      shell: bash

    - id: output
      shell: bash
      run: |
        echo "root-package-version=v$(node -p "require('./package.json')?.version")" >> $GITHUB_OUTPUT
        echo "root-package-major-version=$(node -p "parseInt(require('./package.json')?.version)")" >> $GITHUB_OUTPUT
        echo "is-release-candidate=$(node -p "require('./package.json')?.version?.includes('rc')")" >> $GITHUB_OUTPUT
