name: Action for Cypress
description: Cypress

inputs:
  version:
    description: custom version
    required: true
  deps:
    description: Concrete dependencies instead all
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Detect Cypress version
      id: detect-cy
      shell: bash
      run: |
        VERSION=$(npm ls cypress --all --json 2>/dev/null \
          | jq -r '.. | objects | select(has("version") and has("resolved")) | select(.resolved | contains("cypress")) | .version // empty' \
          | head -n 1)

        echo "version=$VERSION" >> "$GITHUB_OUTPUT"

    - uses: actions/cache@v4.3.0
      id: cypress-cache
      with:
        path: |
          ~/Library/Caches/Cypress
          ~/.cache/Cypress
        key: ${{ runner.os }}-cypress-${{ steps.detect-cy.outputs.version || inputs.version }}

    - name: Clean install Cypress dependencies
      if: steps.cypress-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        npx cypress install ${{ inputs.deps }}