name: Auto remove label
description: Auto remove label

inputs:
  label:
    description: label
    required: false
    default: 'state: need triage'

runs:
  using: composite
  steps:
    - name: Remove labels
      uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0 # v1.3.0
      with:
        labels: ${{ inputs.label }}
