name: 🤖 PR auto merge
on:
  pull_request:

env:
  PR_JOBS_NAME: '[ "ci" ]'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - uses: actions/checkout@v4.2.1
      - uses: taiga-family/ci/actions/setup/variables@main
      - id: matrix
        run: echo "value=$PR_JOBS_NAME" >> $GITHUB_OUTPUT

  wait:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        value: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - uses: taiga-family/ci/actions/run/wait-job@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          job: ${{ matrix.value }}

  approve:
    needs: [wait]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - uses: taiga-family/ci/actions/setup/variables@main
      - uses: taiga-family/ci/actions/auto/approve/double@main
        if: env.IS_TAIGA_FAMILY_BOT_PR_AUTHOR == 'true'
        with:
          token1: ${{ secrets.GITHUB_TOKEN }}
          token2: ${{ secrets.TAIGA_FAMILY_APPROVE_BOT_PAT }}
      - uses: taiga-family/ci/actions/run/merge@main
        if: env.IS_TAIGA_FAMILY_BOT_PR_AUTHOR == 'true'
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
