name: 🤖 Auto approve validation
on: pull_request

env:
  JOBS_NAME: '[ "Lint" ]'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - uses: ./actions/setup/checkout
      - uses: ./actions/setup/variables
      - id: matrix
        if: env.TAIGA_FAMILY_BOT_IS_AUTHOR == 'true'
        run: echo "value=$JOBS_NAME" >> $GITHUB_OUTPUT

  wait:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        value: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - uses: ./actions/run/wait-job
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          job: ${{ matrix.value }}

  approve:
    needs: [wait]
    runs-on: ubuntu-latest
    steps:
      - uses: ./actions/auto/approve/double
        with:
          token1: ${{ secrets.GITHUB_TOKEN }}
          token2: ${{ secrets.TAIGA_FAMILY_APPROVE_BOT_PAT }}
      - uses: ./actions/run/merge
        with:
          token: ${{ secrets.TAIGA_FAMILY_APPROVE_BOT_PAT }}

concurrency:
  group: auto-approve-${{ github.head_ref }}
  cancel-in-progress: true
