name: 🤖 Auto move new issues into Triage
on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: ./actions/setup-project
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
