name: 🤖 Auto cleanup caches
on:
  push:
    branches: [main]
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: ./actions/auto/cleanup-cache
        if: github.event_name == 'push'
        with:
          branch-name: ${{ github.head_ref || github.ref_name }}
      - uses: ./actions/auto/cleanup-cache
        if: github.event_name == 'pull_request'
        with:
          branch-name: refs/pull/${{ github.event.pull_request.number }}/merge
