name: ⚙️ CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: ./actions/setup/variables
      - uses: ./actions/setup/node

      - run: |
          if [[ "${{ env.SUPPORT_AUTO_PUSH }}" == "true" ]]; then
              npm run prettier -- --write
          else
              npm run prettier -- --check
          fi

      - uses: ./actions/auto/push@v1.80.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true
