name: ⚙️ CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
        with:
          persist-credentials: false
      - uses: taiga-family/ci/actions/setup/variables@main
      - uses: taiga-family/ci/actions/setup/node@main

      - run: |
          if [[ "${{ env.SUPPORT_AUTO_PUSH }}" == "true" ]]; then
              npm run prettier -- --write
          else
              npm run prettier -- --check
          fi

      - uses: ./actions/auto/push
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
