name: ⚙️ Lint
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup global variables
        uses: ./actions/variables
      - name: Setup Node.js and Cache
        uses: ./actions/setup-node

      - name: Lint check
        run: |
          npm run prettier -- --check

concurrency:
  group: lint-${{ github.head_ref }}
  cancel-in-progress: true
